### PR TITLE
feat(preview): add send email button

### PR DESCRIPTION
**Pull request by affanshahid**
## Component / Package Name: jsx-email

This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

### Description

This PR ports the "send preview email" feature from react-email using [Resend](https://resend.com/). This is really useful for testing emails in your email client by directly sending them from the preview UI.

image

image

I think this is a really important feature to have but let me know what you think.

I did not add tests because I could not find other tests for the preview app.

### CODE REVIEW

**Comment by lordelogos** [comment]
Hello @affanshahid,

Appreciate your pull request. Nevertheless, we're currently exploring an alternative method to incorporate this feature, steering away from a direct port from react-email.

I'll be closing this now. Feel free to connect on Discord for any questions or inquiries.

**Comment by shellscape** [comment]
A bit premature to close this one.

**Comment by shellscape** [comment]
@affanshahid we've got some things cooking behind the scenes, and would like to integrate your work into it. please hold tight, we're going to leave the PR open but it'll probably go a tad slower than normal for this project.

**Comment by shellscape** [comment]
Good news; we got some info back from a provider we're going to partner with. Will drop some information on the PR here tomorrow.

**Comment by shellscape** [comment]
hey @affanshahid we didn't forget about this. @lordelogos is working on a gist with info for the provider we're going to roll with.

the one bit of feedback I did immediately have was that I'd like to keep the "view selection" button group floated to the right. if you're cool with it, I'd like to move the `Send` button so it's floating over the iframe, under the top bar - similar to how the copy and download buttons are floating over the editor in the code views. I'd also like to change that from `Send` to using the `paper-airplane` icon from https://heroicons.com/. feel free to add some padding or effects to it to draw attention if you'd like to. 

does that sound good?

**Comment by affanshahid** [comment]
Sounds good, I'll make the changes

**Comment by lordelogos** [comment]
Hey @affanshahid 

Here's a doc containing the implementation details
https://gist.github.com/lordelogos/7845d104dc90c066d94068d210be7850

Let me know if you have any questions or need any help

**Comment by affanshahid** [comment]
@lordelogos Just a note, I had to exclude the `from` param in the body otherwise I get a 401. Excluding it works though and the email comes in from the email in the gist.

Also, the provided logo has a white background which looks like this:
Screenshot 2024-01-14 at 5 02 54 PM

Not sure if it would be right to alter SVG to remove the bg but if I do, it looks like this:
Screenshot 2024-01-14 at 5 12 54 PM

If I change the color to match the theme (again, not sure if a good idea), it looks like this:
Screenshot 2024-01-14 at 5 13 46 PM

Let me know which approach you would prefer.

**Comment by lordelogos** [comment]
Hey @affanshahid, 
 Will check out these changes.  Thank you!
 
 (btw, personally I prefer the last option that matches the theme)

**Comment by affanshahid** [comment]
I've changed the icon, this is what the button looks like now:


https://github.com/shellscape/jsx-email/assets/17955210/58d42f1e-ed75-4748-b65d-65f7463691f5



I think we can do without the bounce animation, or at least disable it in the mobile view.

**Comment by shellscape** [comment]
That looks fantastic! I really do love the bounce animation, but agree that we don't need it on the mobile view. Two bounces is probably enough, and probably only when the first email template is opened (not sure how hard that would be to implement). @affanshahid what are your thoughts on that approach?

**Comment by shellscape** [comment]
Also a fan of the "pulse" CTA as well. Totally up to you https://codepen.io/saigowthamr/pen/PowdZqy / https://www.florin-pop.com/blog/2019/03/css-pulse-effect/

**Comment by affanshahid** [comment]
Yes makes sense to only run the animation once or twice. Here's a comparison of bounce vs pulse:

https://github.com/shellscape/jsx-email/assets/17955210/b9a978de-69d1-4132-b3ad-939fbdedb351

https://github.com/shellscape/jsx-email/assets/17955210/2e75fd1b-fab5-4ca5-b055-9459408dc749

Both look fine to me

**Comment by shellscape** [comment]
I'm partial to the pulse, but I'd like to give you the final say 😄

**Comment by affanshahid** [comment]
Pulse it is 👍🏻

**Comment by shellscape** [comment]
awesome. I'll clone your branch here and give things a run through in a bit. this is a huge win for the project!

**Comment by lordelogos** [comment]
Hey guys, 

I know i'm late to the party but I'm for bounce

especially the 2 bounces at the start
@affanshahid @shellscape

**Comment by shellscape** [comment]
@affanshahid you've got two different opinions from maintainers haha 😆 as the PR author I think it's fair for you to be the deciding vote!

**Comment by affanshahid** [comment]
I think the pulse might be more attention grabbing, so let's go with that for now.

**Comment by shellscape** [comment]
@affanshahid had the chance to check out your branch tonight. everything worked great!

I've got one more request, if you're up for it: when the `Send` button is clicked, could we show an animation on the button and change the color to indicate that it's disabled while we wait for the API call to complete? And when the API call completes, change the dialog (or an overlay) to a message like "Your template was sent!" and then close the dialog?

**Comment by shellscape** [comment]
just checked out those changes and they look awesome. thanks for adding that!

**Comment by affanshahid** [comment]
This is what it looks like now:

https://github.com/shellscape/jsx-email/assets/17955210/4baa0093-40a9-49c9-935d-605a3b417654

**Pull request merged**
